sudo: false
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm prune
after_success:
  - npm run report-coverage
notifications:
  webhooks:
    urls:
      secure: "EJhCloHuAsbw4G1YOHF7HB7QEzY9XvHBsljbF+zBWhg4pDUz+rVjqKWwSoqdXlEo6YBjpGK19UYZEu68yBNLdVW9JshEN/rLsdp1DoWTGwmzjqQXTPY7t+JT/Al71KnVDfUzaZ+pYGSJKsSflOn+AYQ5unqCQxYCCYpEsVxOLCRKj6kUB4U4c56j6+SuFWyynP23YAmAgUD4ey351PlQTk21ghivNqw/+ucoCh0eXrqfdVUmUPNMK+byWBb2nK5Xl+LJ5a7YXp3mVHndWX7hPue3BUlh4Tp4enNHvMPh4p7ddO3sN+ahiE7sZI0qz4T4D+mpHnOCR4dFiLpwlCIoIJazzWNt4+VQ2TjGGraQ9JNDCr1QFfKdKiR9L7efnlok8bzGTxlUGrvIhMvTVz2eGmmBKY5TW8P7w4ZymzM7lGWvrhuImcQAaxQHjny5P1K0ao8rXntnpEKjdPJW3VTeF8t6C73NzP1teov7xtYtVrQ8UsAGIdRhM/+b11K94mam36BFoS7ZI15t97F0lLI4P5zSmDmK0yVqlQ1F2aekjhM64qetKYgOVyScG3S87dciDBTi9mY/z4YnA0h09nZbjgddTbb1IhibDEp1H/BxnQWhU13L26XntbORydqn8BBxCEnvluDxieDk/+vVeKAbh0QPcCmynoXErewKdV6x9Gk="
